CREATE TABLE user_otps (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL,
    otp TEXT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    expires_at DATETIME GENERATED ALWAYS AS (DATETIME(created_at, '+30 minutes')) STORED,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
